version: '3.8'

services:
  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: goexpert
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - net_mariadb

volumes:
  mariadb_vol:

networks:
  net_mariadb:
    driver: bridge